#ifndef MODULES_H
#define MODULES_H

// version 1.0
#include "adsr.h"
#include "clockclock.h"
#include "constmod.h"
#include "freqgenerator.h"
#include "lfoclock.h"
#include "lfocontroller.h"
#include "lowpassfilter.h"
#include "modifier.h"
#include "noisegenerator.h"
#include "oscclock.h"
#include "samplehold.h"
#include "sampler.h"
#include "sequencer.h"
#include "sinewave.h"
#include "squarewave.h"
#include "stereoamp.h"
#include "stereochannel.h"
#include "stereomixer.h"
#include "trianglewave.h"
#include "trianglewave2.h"
#include "trigger.h"
#include "userwave.h"
#include "wavfileout.h"
#include "randomtrigger.h"
#include "logictrigger.h"
#include "switcher.h"
#include "highpassfilter.h"
#include "combiner.h"
#include "nonezero.h"
// version 1.1000
#include "timemap.h"
#include "serialwavfileout.h"
#include "contraster.h"
#include "delay.h"
#include "echo.h"
#include "monoamp.h"
#include "wcntmodule.h"
#include "multiplier.h"
#include "rangelimit.h"
#include "pan.h"
#include "rms.h"
#include "dc_filter.h"
// version 1.1z
#include "dynamic.h"
#include "spreader.h"
#include "notetran.h"
// version 1.127
#include "waittrig.h"
#include "patterntrig.h"
#include "stategatetrig.h"
#include "invert.h"
#include "timer.h"
// version 1.128
#include "syncclock.h"
// version 1.2
#include "wcnttrigger.h"
#include "trigswitcher.h"
#include "onofftrig.h"

#endif
