#ifndef PARAMNAMES_H
#define PARAMNAMES_H

#include <string>
#include "iocat.h"


class paramnames
{
 public:
	enum PAR_TYPE
	{
		PAR_FIRST = 0,
		PAR_SUSTAIN_STATUS,
		PAR_ZERO_RETRIGGER,
		PAR_NOTELEN_FREQ,
		PAR_FREQ,
		PAR_FREQ_MOD1SIZE,
		PAR_FREQ_MOD2SIZE,
		PAR_VALUE,
		PAR_SIG_RANGE_HI,
		PAR_SIG_RANGE_LO,
		PAR_FREQ_RANGE_HI,
		PAR_FREQ_RANGE_LO,
		PAR_STEP_COUNT,
		PAR_DELAY_TIME,
		PAR_RAMP_TIME,
		PAR_START_LEVEL,
		PAR_END_LEVEL,
		PAR_AMP_MODSIZE,
		PAR_RES_LEVEL,
		PAR_RES_AMP_MODSIZE,
		PAR_MODIFIER_FUNC, 
		PAR_MODIFIER_SIZE,
		PAR_MIN_OUT,
		PAR_MAX_OUT,
		PAR_POSNEG_MIRROR,
		PAR_FREQ_MOD1_LO,
		PAR_FREQ_MOD1_HI,
		PAR_FREQ_MOD2_LO,
		PAR_FREQ_MOD2_HI,
		PAR_OCTAVE,
		PAR_PORTAMENTO,
		PAR_DECAY_TIME,
		PAR_START_POS_MIN,
		PAR_START_POS_MAX,
		PAR_LOOP_BEGIN,
		PAR_LOOP_END,
		PAR_LOOP_MODE,
		PAR_ANTI_CLIP,
		PAR_ROOT_NOTE,
		PAR_ROOT_FREQ,
		PAR_ROOT_DEGSIZE,
		PAR_DEGSIZE_AMOUNT,
		PAR_RECYCLE_MODE,
		PAR_TRIG_ZERO_DEG,
		PAR_CYCLES,
		PAR_PULSE_WIDTH,
		PAR_PWM_SIZE,
		PAR_AMPLITUDE,
		PAR_PAN,
		PAR_PAN_MODSIZE,
		PAR_CLIP_MODE, 
		PAR_CLIP_LEVEL,
		PAR_DC_LEVEL,
		PAR_MASTER_LEVEL,
		PAR_NORM_FREQ,
		PAR_NORM_MOD_HI,
		PAR_NORM_MOD_LO,
		PAR_TRIGGER_LEVEL,
		PAR_FILENAME,
		PAR_WAVFILEIN,
		PAR_WRITE_FROM_BAR,
		PAR_WRITE_TO_BAR,
		PAR_WRITE_FROM_SAMPLE,
		PAR_WRITE_TO_SAMPLE,
		PAR_VELOCITY_RESPONSE,
		PAR_PROBABILITY,
		PAR_NOTPROBABILITY,
		PAR_LOGICFUNC,
		PAR_XFADE_TIME,
		PAR_TUNING_SEMITONES,
		PAR_MEAN_TOTAL,
		PAR_LAST
	};
	
	paramnames();
	~paramnames();
	string getname(PAR_TYPE);
	IOCAT getcategory(PAR_TYPE);
	PAR_TYPE get_type(string const*);
 private:
	string* parname;
	IOCAT* parcat;
	
};

#endif
