#include "../include/paramnames.h"

namespace param
{
 const struct names::gn_data names::data[LAST_TYPE] =
 {
    { ERR_TYPE,         "BAD_PARAM_TYPE",       iocat::ERR_TYPE,"ERROR!"   ,0 },
    { SUSTAIN_STATUS,   "sustain_state",        iocat::STATE,   "Set sustain section to be active or ignored." ,0 },
    { ZERO_RETRIGGER,   "zero_retrigger",       iocat::STATE,   "Whether to hard reset to zero on retrigger." ,0 },
    { FREQ,             "freq",                 iocat::DOUBLE,  "Operating frequency." ,0 },
    { FREQ_MOD1SIZE,    "freq_mod1_size",       iocat::DOUBLE,  "Modulation amount using 1st modulation input." ,0 },
    { FREQ_MOD2SIZE,    "freq_mod2_size",       iocat::DOUBLE,  "Modulation amount using 2nd modulation input." ,0 },
    { VALUE,            "value",                iocat::DOUBLE,  "Output value." ,0 },
    { SIG_RANGE_HI,     "sig_range_hi",         iocat::DOUBLE,  "Maximum allowed input level." ,0 },
    { SIG_RANGE_LO,     "sig_range_lo",         iocat::DOUBLE,  "Minimum allowed input level." ,0 },
    { FREQ_RANGE_HI,    "freq_range_hi",        iocat::DOUBLE,  "Maximum frequency to output." ,0 },
    { FREQ_RANGE_LO,    "freq_range_lo",        iocat::DOUBLE,  "Minimum frequency to output." ,0 },
    { STEP_COUNT,       "step_count",           iocat::WCINT_T, "Number of steps to split allowed output values into." ,0 },
    { DELAY_TIME,       "delay_time",           iocat::DOUBLE,  "Length of delay time (ms)." ,0 },
    { RAMP_TIME,        "ramp_time",            iocat::DOUBLE,  "Length of time to ramp up to full output levels (ms)." ,0 },
    { START_LEVEL,      "start_level",          iocat::DOUBLE,  "Start output level." ,0 },
    { END_LEVEL,        "end_level",            iocat::DOUBLE,  "End output level." ,0 },
    { AMP_MODSIZE,      "amp_mod_size",         iocat::DOUBLE,  "Amplitude modulation amount." ,0 },
    { FUNC,             "function",             iocat::FIX_STR, "Math function to apply." ,0 },
    { POSNEG_MIRROR,    "posneg_mirror",        iocat::STATE,   "Whether to mirror positive values to negative and vice-versa." ,0 },
    { OCTAVE,           "octave_offset",        iocat::WCINT_T, "Number of octaves to adjust frequency." ,0 },
    { PORTAMENTO,       "portamento_time",      iocat::DOUBLE,  "Length of time (ms) to slide/portamento effect should last." ,0 },
    { DECAY_TIME,       "decay_time",           iocat::DOUBLE,  "Length of time (ms) decay should last." ,0 },
    { START_POS,        "start_pos",            iocat::DOUBLE,  "Start position (samples)." ,0 },
    { START_POS_MIN,    "start_pos_min",        iocat::SAMP_T,  "Minimum start position (samples)." ,0 },
    { START_POS_MAX,    "start_pos_max",        iocat::SAMP_T,  "Maximum start position (samples)." ,0 },
    { LOOP_BEGIN,       "loop_start_pos",       iocat::SAMP_T,  "Start position of loop (samples)." ,0 },
    { LOOP_END,         "loop_end_pos",         iocat::SAMP_T,  "End of loop position (samples)." ,0 },
    { LOOP_MODE,        "loop_mode",            iocat::FIX_STR, "Loop mode." ,0 },
    { XFADE_SAMPLES,    "xfade_samples",        iocat::WCINT_T, "Number of samples to x-fade when playback starts or looping occurs." ,0 },
    { PHASE_STEP_AMOUNT,"phase_step_amount",    iocat::DOUBLE,  "Amount to adjust phase step. Should be set to 1.0 for normal operation." ,0 },
    { RECYCLE_MODE,     "recycle_mode",         iocat::STATE,   "Whether to loop continuously or not." ,0 },
    { TRIG_RESET_PHASE, "on_trig_reset_phase",  iocat::STATE,   "Whether to hard-reset phase on re-trigger (may cause clicks, depends on usage)." ,0 },
    { CYCLES,           "phase_cycles",         iocat::DOUBLE,  "Amount of phase cycle(s) to run through, 1.0 for normal operation." ,0 },
    { PULSE_WIDTH,      "pulse_width",          iocat::DOUBLE,  "Pulse width, 0.5 for equal width positive and negative phase pulses.",0 },
    { PWM_SIZE,         "pwm_size",             iocat::DOUBLE,  "Pulse Width Modulation amount." ,0 },
    { PAN,              "pan",                  iocat::DOUBLE,  "Pan position, -1.0 = left, 0.0 = center, +1.0 = right." ,0 },
    { PAN_MODSIZE,      "pan_mod_size",         iocat::DOUBLE,  "Pan modulation amount. ",0 },
    { CLIP_LEVEL,       "clip_level",           iocat::DOUBLE,  "Level to clip amplitude at, 1.0 is a fairly sane value - perhaps." ,0 },
    { NORM_FREQ,        "normal_freq",          iocat::DOUBLE,  "Frequency the waveform considers it normal to operate at." ,0 },
    { NORM_MODSIZE,     "norm_mod_size",        iocat::DOUBLE,  "Modulation amount of the normal operating frequency." ,0 },
    { TRIGGER_LEVEL,    "trigger_level",        iocat::DOUBLE,  "Signal level which will cause trigger output." ,0 },
    { FILENAME,         "filename",             iocat::STRING,  "Path of file. Can NOT specify a path containing spaces characters." ,0 },
    { WAVFILEIN,        "wavfile",              iocat::DOBJ,    "Name of the wavfilein data object to obtain audio from." ,0 },
    { VELOCITY_RESPONSE,"velocity_response_time",iocat::DOUBLE, "How fast (ms) to respond to velocity changes." ,0 },
    { PROBABILITY,      "probability",          iocat::DOUBLE,  "Probability of something occurring: 0.0 = never, 1.0 = always." ,0 },
    { NOTPROBABILITY,   "not_probability",      iocat::DOUBLE,  "Probability of something having not occurred, to occur as something else: 0.0 = never, 1.0 = always." ,0 },
    { LOGICFUNC,        "function",             iocat::FIX_STR, "Logic function to use." ,0 },
    { XFADE_TIME,       "xfade_time",           iocat::DOUBLE,  "Cross fade time (ms)." ,0 },
    { TUNING_SEMITONES, "tuning_semitones",     iocat::DOUBLE,  "Semitone amount to tune frequency, can be fractional." ,0 },
    { MEAN_TOTAL,       "mean_total",           iocat::STATE,   "Whether to apply mean average to signals." ,0 },
    { WAV_BASENAME,     "basename",             iocat::STRING,  "Basename of WAV filename, a four digit number will be appended to this." ,0 },
    { PLAY_DIR,         "play_dir",             iocat::FIX_STR, "Play direction to start with." ,0 },
    { PLAY_MODE,        "play_mode",            iocat::FIX_STR, "TODO: figure out how this works..." ,0 },
    { JUMP_MODE,        "jump_mode",            iocat::FIX_STR, "TODO: figure out how this works..." ,0 },
    { LOOP_IS_OFFSET,   "loop_is_offset",       iocat::STATE,   "Whether to treat loop_start and loop_end as offsets to actual start position when triggered." ,0 },
    { LOOP_BI_OFFSET,   "bi-directional_offset",iocat::WCINT_T, "Number of samples to offset when reaching loop points of bi-directional loop." ,0 },
    { XFADE_EACH_END,   "xfade_each_end",       iocat::STATE,   "Whether to xfade at start and end of audio file." ,0 },
    { POWER,            "power",                iocat::DOUBLE,  "Amount of contrast to apply, 0.0 is none." ,0 },
    { POWER_MIN,        "power_min",            iocat::DOUBLE,  "Minimum amount of contrast to apply, 0.0 is none." ,0 },
    { POWER_MAX,        "power_max",            iocat::DOUBLE,  "Maximum amount of power to apply, more is more. " ,0 },
    { RUDE_MODE,        "rude_mode",            iocat::STATE,   "Whether to use the rude mode or not, the improper implementation." ,0 },
    { WETDRY,           "wet/dry",              iocat::DOUBLE,  "How much of the wet signal to apply, 0.0 ~ 1.0." ,0 },
    { START_BAR,        "start_bar",            iocat::WCINT_T, "Bar number (0 = first bar) to start processing on." ,0 },
    { END_BAR,          "end_bar",              iocat::WCINT_T, "Bar number (0 = first bar) to end processing on." ,0 },
    { ZERO_SEARCH_RANGE,"zero_search_range",    iocat::WCINT_T, "Number of samples to search around play/loop points for zero-crossing. " ,0 },
    { GAIN,             "gain",                 iocat::DOUBLE,  "Gain value, 0.0 = silence, 1.0 = no gain, > 1.0 = gain. ",0 },
    { GAIN_MODSIZE,     "gain_mod_size",        iocat::DOUBLE,  "Gain modulation amount." ,0 },
    { FEED_LEVEL,       "feedback",             iocat::DOUBLE,  "Amount of feedback. 0.0 = none, 1.0 = 100%." ,0 },
    { FEED_MODSIZE,     "feedback_mod_size",    iocat::DOUBLE,  "Feedback modulation amount." ,0 },
    { EXIT_BAR,         "exit_bar",             iocat::WCINT_T, "Bar to stop all processing and exit the program at." ,0 },
    { RESPONSE_TIME,    "response_time",        iocat::DOUBLE,  "Length of time (ms) taken to respond to input." ,0 },
    { RMS_TIME,         "rms_time",             iocat::DOUBLE,  "Length of time (ms) to calculate the Root Mean Square over." ,0 },
    { DC_TIME,          "dc_time",              iocat::DOUBLE,  "Length of time (ms) to calculate the mean over." ,0 },
    { UP_THRESH,        "up_thresh",            iocat::DOUBLE,  "Threshold level of modulation input causing usage of upper shape." ,0 },
    { LO_THRESH,        "lo_thresh",            iocat::DOUBLE,  "Threshold level of modulation input causing usage of lower shape." ,0 },
    { LEVEL,            "level",                iocat::DOUBLE,  "Signal level to let through, 0.0 = none, 1.0 = 100%." ,0 },
    { ATTACK_TIME,      "attack_time",          iocat::DOUBLE,  "Length of time (ms) to take to reach attack level." ,0 },
    { ATTACK_LEVEL,     "attack_level",         iocat::DOUBLE,  "Amplitude level to reach by end of attack stage." ,0 },
    { RELEASE_TIME,     "release_time",         iocat::DOUBLE,  "Length of time (ms) to reach release level." ,0 },
    { RELEASE_LEVEL,    "release_level",        iocat::DOUBLE,  "Amplitude level to reach at end of release stage." ,0 },
    { USE_RATIOS,       "use_ratios",           iocat::STATE,   "Whether the shape levels should be applied as ratios or not." ,0 },
    { NO_LONOTE,        "no_lo_notename",       iocat::STRING,  "Lowest note-name to accept from note-on." ,0 },
    { NO_HINOTE,        "no_hi_notename",       iocat::STRING,  "Highest note-name to accept from note-on." ,0 },
    { NS_LONOTE,        "ns_lo_notename",       iocat::STRING,  "Lowest note-name to accept from note-slide." ,0 },
    { NS_HINOTE,        "ns_hi_notename",       iocat::STRING,  "Highest note-name to accept from note-slide." ,0 },
    { MINNO_OUT,        "min_no_out",           iocat::DOUBLE,  "Minimum value to output from minimum note-on event." ,0 },
    { MAXNO_OUT,        "max_no_out",           iocat::DOUBLE,  "Maximum value to output from minimum note-on event." ,0 },
    { MINNS_OUT,        "min_ns_out",           iocat::DOUBLE,  "Minimum value to output from minimum note-slide event." ,0 },
    { MAXNS_OUT,        "max_ns_out",           iocat::DOUBLE,  "Maximum value to output from minimum note-slide event." ,0 },
    { DETRAN_NO,        "detranspose_no",       iocat::STATE,   "Whether to detranspose note-on events before processing them." ,0 },
    { DETRAN_NS,        "detranspose_ns",       iocat::STATE,   "Whether to detranspose note-slide events before processing them." ,0 },
    { NO_RESPTIME,      "no_response_time",     iocat::DOUBLE,  "Length of time (ms) to respond to note-on." ,0 },
    { NS_RESPTIME,      "ns_response_time",     iocat::DOUBLE,  "Length of time (ms) to respond to note-slide." ,0 },
    { MIN_WAIT,         "min_wait_time",        iocat::DOUBLE,  "Minimum amount of time (ms) to wait before processing." ,0 },
    { MAX_WAIT,         "max_wait_time",        iocat::DOUBLE,  "Maximum amount of time (ms) to wait before processing." ,0 },
    { TRIG_STRING,      "pattern",              iocat::STRING,  "Trigger pattern to use, 0 = do not trigger, 1 = trigger." ,0 },
    { QUARTER_VAL,      "quarter_value",        iocat::WCINT_T, "Ticks Per Quarter Note (often a value divisible by both 3 and 4)." ,0 },
    { RELEASE_RATIO,    "release_is_ratio",     iocat::STATE,   "Generally should mostly be set to on." ,0 },
    { MIN_TIME,         "min_time",             iocat::DOUBLE,  "Minium time (ms) before allowing release stage to activate." ,0 },
    { MAX_SUSTAIN_TIME, "max_sustain_time",     iocat::DOUBLE,  "Maximum time (ms) sustain section should last. 0.0 for no restriction.",0 },
    { PRECISION,        "precision",            iocat::WCINT_T, "Number of samples apart the two inputs may trigger to still be considered simultaneous." ,0 },
    { NAME,             "name",                 iocat::STRING,  "Name.",0 },
    { NOTE_POS,         "pos",                  iocat::DOUBLE,  "Position of note in bar, relative to TPQN of riff." ,0 },
    { NOTE_LEN,         "len",                  iocat::DOUBLE,  "Length of note, relative to TPQN of riff." ,0 },
    { NOTE_VEL,         "vel",                  iocat::DOUBLE,  "Velocity of note, consider 1.0 as full velocity." ,0 },
    { ADSRSECT,         "name",                 iocat::FIX_STR, "ADSR section to define." ,0 },
    { TIME,             "time",                 iocat::DOUBLE,  "time (ms)." ,0 },
    { UPTIME,           "ut",                   iocat::DOUBLE,  "Upper shape section time (ms)." ,0 },
    { LOTIME,           "lt",                   iocat::DOUBLE,  "Lower shape section time (ms)." ,0 },
    { UPLEVEL,          "ul",                   iocat::DOUBLE,  "Upper shape section level." ,0 },
    { LOLEVEL,          "ll",                   iocat::DOUBLE,  "Lower shape section level.",0 },
    { DEG,              "deg",                  iocat::DOUBLE,  "shape section degree (0 ~ 360)." ,0 },
    { UPDEG,            "ud",                   iocat::DOUBLE,  "Upper shape section degree (0 ~ 360)." ,0 },
    { LODEG,            "ld",                   iocat::DOUBLE,  "Lower shape section degree (0 ~ 360)." ,0 },
    { METER,            "tsig",                 iocat::METER,   "Time signature/Meter, ie 4/4 or 3/8 etc." ,0 },
    { BAR,              "bar",                  iocat::WCINT_T, "Bar number (starting at 0)." ,0 },
    { BPM,              "bpm",                  iocat::DOUBLE,  "Tempo as Beats Per Minute." ,0 },
    { RIFFNAME,         "riff",                 iocat::DOBJ,    "Name of riff to use." ,0 },
    { MODNAME,          "name",                 iocat::SYNTHMOD,"Name of module to use." ,0 },
    { ROOT_NOTE,        "root_note",            iocat::STRING,  "Root note of sample when playing at its natural rate." ,0 },
    { TRANSPOSE,        "transpose",            iocat::WCINT_T, "Number of semitones to transpose the notes (none-fractional)." ,0 },
    { SIGIN_LEVEL,      "sigin_level",          iocat::DOUBLE,  "Adjust input signal level, 1.0 = no adjustment." ,0 },
    { SIGOUT_LEVEL,     "so_level",             iocat::DOUBLE,  "shape output level." ,0 },
    { SIGOUT_UPLEVEL,   "so_ul",                iocat::DOUBLE,  "Upper shape output level." ,0 },
    { SIGOUT_LOLEVEL,   "so_ll",                iocat::DOUBLE,  "Lower shape output level." ,0 },
    { SECONDS,          "seconds",              iocat::DOUBLE,  "Number of seconds to wait." ,0 },
    { MOD_ACTION,       "mod_action",           iocat::FIX_STR, "What to do with modules named in the list." ,0 },
    { DOBJ_ACTION,      "dobj_action",          iocat::FIX_STR, "What to do with data objects named in the list.",0 },
    { SNAP_TO,          "snap_to",              iocat::DOUBLE,  "Multiple, relative to TPQN (quarter_value), to snap positions to." ,0 },
    { COUNT,            "count",                iocat::WCINT_T, "The number of what-have-yous to do and see." ,0 },
    { CHECK_LEVELS,     "check_levels",         iocat::STATE,   "Whether to perform extra checks on the levels or not." ,0 },
    { MSG,              "message",              iocat::STRING,  "A message to display during processing." ,0 },
    { FORCE_ABORT,      "force_abort",          iocat::STATE,   "Whether to force wcnt to abort after so many detected peaks." ,0 },
    { MAXPEAKS,         "max_peaks",            iocat::WCINT_T, "Maximum number of peaks that may be detected before message display stopped or forced abort." ,0 },
    { REPEAT,           "repeat",               iocat::WCINT_T, "How many times to repeat the riff along bars in the timeline." ,0 },
    { REPEAT_STRIPE,    "repeat_stripe",        iocat::WCINT_T, "Repeat every n bars." ,0 },
    { COPYFROM,         "from",                 iocat::STRING,  "Name of module or data object to copy." ,0 },
    { COPYTO,           "to",                   iocat::STRING,  "Name of new module or data object created by copy." ,0 },
    { POS,              "pos",                  iocat::DOUBLE,  "Position 0.0 ~ 1.0." ,0 },
    { BIAS,             "bias",                 iocat::DOUBLE,  "Bias between two signals, 0.0 ~ 1.0." ,0 },
    { ORBIT_TYPE,       "orbit_type",           iocat::FIX_STR, "Type of orbit fractal to calculate." ,0 },
    { A,                "a",                    iocat::DOUBLE,  "Parameter A of orbit fractal." ,0 },
    { B,                "b",                    iocat::DOUBLE,  "Parameter B of orbit fractal." ,0 },
    { C,                "c",                    iocat::DOUBLE,  "Parameter C of orbit fractal." ,0 },
    { TEST_ITER,        "test_iterations",      iocat::SAMP_T,  "Number of fractal iterations to perform to obtain an output scaling ratio in attempt to limit output within -1.0 ~ +1.0 range." ,0 },
    { DATA_FMT,         "data_format",          iocat::FIX_STR, "Data format of audio file to be written." ,0 },
    #ifdef WITH_LADSPA
    { GLAME_FILTER_TYPE,"filter_type",          iocat::FIX_STR, "The type of filter to use." ,0 },
    { RESONANCE,        "resonance",            iocat::DOUBLE,  "The resonance amount." ,0 },
    { RES_MODSIZE,      "res_mod_size",         iocat::DOUBLE,  "Resonance modulation amount." ,0 },
    { GAIN_DB,          "gain_db",              iocat::DOUBLE,  "Gain amount, in decibels." ,0 },
    { LIMIT_DB,         "limit_db",             iocat::DOUBLE,  "dB Limit." ,0 },
    { RELEASE_SECS,     "release_secs",         iocat::DOUBLE,  "Release time (seconds)." ,0 },
    { THRESH_DB,        "threshold_db",         iocat::DOUBLE,  "Threshold dB." ,0 },
    { RATIO_1N,         "ratio_1:n",            iocat::DOUBLE,  "Ratio, 1 to n, where n is..." ,0 },
    { KNEE_DB,          "knee_db",              iocat::DOUBLE,  "Knee dB." ,0 },
    { MAKEUP_DB,        "makeup_db",            iocat::DOUBLE,  "Make-up dB," ,0 },
    { BANDWIDTH,        "bandwidth",            iocat::DOUBLE,  "Bandwidth of input sent through reverb." ,0 },
    { BANDWIDTH_MODSIZE,"bandwidth_mod_size",   iocat::DOUBLE,  "Bandwidth modulation amount." ,0 },
    { STAGES,           "stages",               iocat::WCINT_T, "Number of filter stages." ,0 },
    { FREQ_SHIFT,       "freq_shift",           iocat::DOUBLE,  "Amount to frequency shift." ,0 },
    { SHIFT_MODSIZE,    "shift_mod_size",       iocat::DOUBLE,  "Frequency shift modulation amount." ,0 },
    { TAIL,             "tail",                 iocat::DOUBLE,  "Length of reverb tail.." ,0 },
    { DAMPING,          "damping",              iocat::DOUBLE,  "Amount of reverb damping." ,0 },
    #endif
    { ADSR_NAME,        "adsr_name",            iocat::SYNTHMOD,"Name of the ADSR to scale." ,0 },
    { ATTACK_SCALE,     "attack_scale",         iocat::DOUBLE,  "Amount to scale the ADSR attack section by."   ,0 },
    { DECAY_SCALE,      "decay_scale",          iocat::DOUBLE,  "Amount to scale the ADSR decay section by." ,0 },
    { RELEASE_SCALE,    "release_scale",        iocat::DOUBLE,  "Amount to scale the ADSR release section by." ,0 },
    { WAVE_TYPE,        "type",                 iocat::FIX_STR, "Waveform type."  ,0 },
    { WAVE_SHAPE_TYPE,  "shape_type",           iocat::FIX_STR, "Waveform type of shaping function." ,0 },
    { INVERT_ALT,       "invert_alt",           iocat::STATE,   "Whether to invert sign of alternate phases (note: only useful with abnormal-phase-length waveforms)." ,0 },
    { SYNC_SHAPE,       "sync_shape",           iocat::STATE,   "Whether to sync shaping waveform."    ,0 },
    { MODIFIER_TYPE,    "type",                 iocat::FIX_STR, "Math operator type for applying the two signals together." ,0 },
    { SEND_INPUT_OUT,   "send_input_out",       iocat::STATE,   "Whether to directly output the input trigger also." ,0 },
    { INSPECT_DF_MSG,   "_float_msg_",          iocat::STRING,  "Message to display when a floating point value is triggered."  ,0 },
    { INSPECT_SI_MSG,   "_int_msg_",            iocat::STRING,  "Message to display when a integer value triggered."  ,0 },
    { INSPECT_UL_MSG,   "_sample_msg_",         iocat::STRING,  "Message to display when a sample position value triggered."  ,0 },
    { INSPECT_ST_MSG,   "_state_msg_",          iocat::STRING,  "Message to display when a state value triggered."  ,0 },
    { INSPECT_STR_MSG,  "_string_msg_",         iocat::STRING,  "Message to display when a string value triggered."  ,0 },
    { PRE_COUNT,        "pre_count",            iocat::WCINT_T,   "How many triggers to ignore before counting." ,0 },
    { WRAP,             "wrap",                 iocat::STATE,   "Whether to start counting over again after reaching desired count of triggers, even if not reset by reset trigger."   ,0 },
    { GROUP_NAME,       "group_name",           iocat::STRING,  "Name of group to control."  ,0 },
    { FADE_IN_TIME,     "fade_in_time",         iocat::DOUBLE,  "Length of time (ms) that fade in should take."  ,0 },
    { FADE_OUT_TIME,    "fade_out_time",        iocat::DOUBLE,  "Length of time (ms) that fade out should take."  ,0 },
    { RATE,             "rate",                 iocat::DOUBLE,  "Rate that target level should be reached, ie output = output + (target - output) * rate." ,0 },
    { SNAPSHOT_MODE,    "snapshot_mode",        iocat::STATE,   "Whether to append a timestamp to filenames of written audio files." ,0 },
    { DROP_CHECK_RANGE, "drop_check_range",     iocat::WCINT_T, "How may degrees apart a pair of vertices may be to considered a collision and for one to be dropped from waveform. " ,0 },
    { STR_UNNAMED,      "<unnamed_item>",       iocat::STRING,  "A name of something." ,0 },
    { STR_LIST,         "<unnamed_list>",       iocat::STRING,  "A number of names of things." ,0 },
    { TIME_IS_RELATIVE, "time_is_relative",     iocat::STATE,   "Whether the specified times should be treated as relative to each other, or as absolute times." ,0 },
    { START_PHASE,      "start_phase",          iocat::DOUBLE,  "Position within phase cycle to start. Range 0.0 ~ 1.0" ,0 },
    { SHAPE_START_PHASE,"shape_start_phase",    iocat::DOUBLE,  "Position within phase cycle to start. Range 0.0 ~ 1.0" ,0 },
    { ZERO_WHEN_OFF,    "zero_when_off",        iocat::STATE,   "Forces output to zero when play state is off." ,0 },
    { PHASE_MOD_SIZE,   "phase_mod_size",       iocat::DOUBLE,  "Amount of phase modulation to apply 0.0 for none." ,0 },
    { EG_AMOUNT,        "eg_amount",            iocat::DOUBLE,  "How much effect the Envelope Generator has. 1.0 normal full effect. Range 0.0 ~ 1.0" ,0 },
    { CONNECT,          "connect",              iocat::STRING,  "Name of module for connecting the outputs of with the input group which follows." ,0 },
    { OUTPUT,           "output",               iocat::STRING,  "name of specific output when default does not work.", 0 },
    { BALANCE,          "balance",              iocat::DOUBLE,  "Balance of left & right signals. -1 all left no right, 0 both left and right, +1, all right no left.", 0 },
    { BPM_CHANGES_REL,  "bpm_changes_relative", iocat::STATE,   "whether bpm changes are relative (on) or absolute values (off)", 0 }

 };
}; // namespace param
